apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routebird-agent-sa
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
