apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: routebird

profiles:
  - name: agent-only
    build:
      artifacts:
        - image: yagodev123/routebird-agent
          docker:
            dockerfile: Dockerfile.agent
    manifests:
      kustomize:
        paths:
          - config/skaffold-dev
