apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: routebird

build:
  artifacts:
    - image: yagodev123/routebird-agent
      docker:
        dockerfile: Dockerfile.agent
    - image: yagodev123/routebird-controller
      docker:
        dockerfile: Dockerfile.controller
  local:
    push: false  # Avoid pushing to remote registries during local development
  tagPolicy:
    sha256: {}  # This will tag images using their SHA (ensures unique tags for each build)

manifests:
  kustomize:
    paths:
      - ./config/default/

deploy:
  kubectl: {}

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false
