# This rule is not used by the project routebird itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to bgp.routebird.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: routebird
    app.kubernetes.io/managed-by: kustomize
  name: bgproute-viewer-role
rules:
- apiGroups:
  - bgp.routebird.dev
  resources:
  - bgproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bgp.routebird.dev
  resources:
  - bgproutes/status
  verbs:
  - get
