---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bgp.routebird.dev
  resources:
  - bgproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bgp.routebird.dev
  resources:
  - bgproutes/finalizers
  verbs:
  - update
- apiGroups:
  - bgp.routebird.dev
  resources:
  - bgproutes/status
  verbs:
  - get
  - patch
  - update
